### ISSUE TITLE
JsonConvert does not work on .NET 8.0.101

### ISSUE THREAD

**Issue by vmetodiev** [NexarDeveloper/nexar-first-supply-query#12]
When _using System.Text.Json_, VS Code reports that _**JsonConvert**_ could not be found.

Workaround: Use _Newtonsoft.Json_ instead.

![JsonIssueDotNet](https://github.com/NexarDeveloper/nexar-first-supply-query/assets/9915101/451c5da9-f51a-484a-8634-5f0797b5e223)

**Comment by nightroman** [comment]
There is no `JsonConvert` of Newtonsoft in our code:

![image](https://github.com/NexarDeveloper/nexar-first-supply-query/assets/927533/997fbb10-f169-445e-aa12-32a9cbf0f74e)

https://github.com/NexarDeveloper/nexar-first-supply-query/blob/d58640ce6bb6de9f21850f0feb3c5dd0176d69ac/c%23/SupplyQueryDemo/SupplyQueryDemo/SupplyClient.cs#L37

**Comment by nightroman** [comment]
If you need `JsonConvert` of Newtonsoft (kind of legacy), add the package reference to your project and use `JsonConvert`. It is fine using both modern `System.Text.Json` and legacy `Newtonsoft.Json`, if it is what you need.
