### ISSUE TITLE
API content-type changed, check is failing

### ISSUE THREAD

**Issue by burritojustice** [NexarDeveloper/nexar-first-supply-query#8]
We just noticed the API is now returning `application/graphql-response+json` for `content-type` -- before it was returning `application/json`.

If this is permanent, you should modify this `content-type` check

https://github.com/NexarDeveloper/nexar-first-supply-query/blob/381cf2c2aad5312cdf3c40cc479fcbc04450e46a/javascript/NexarClient/nexarClient.js#L33

**Comment by RowMur** [comment]
Hi, I've just adapted the regex to check for `application/graphql-response+json` also. Thank you for pointing this out.
