### ISSUE TITLE
Cannot get token exception

### ISSUE THREAD

**Issue by vmetodiev** [NexarDeveloper/nexar-first-supply-query#9]
I have an evaluation app within the "Supply" scope. After setting the NEXAR_CLIENT_ID and NEXAR_CLIENT_SECRET environment variables. the result is:

Unhandled exception. System.InvalidOperationException: Cannot get Nexar token.
   at Nexar.Client.Token.HttpClientExtensions.GetNexarTokenAsync(HttpClient httpClient, String clientId, String clientSecret, String authority)

**Comment by RobAltium** [comment]
Hi @vmetodiev 
Please can you send some specifics - e.g. which set-up are you using, which query do you want to me?

I'd recommend going through the first supply query guide if you haven't already done so:
https://support.nexar.com/support/solutions/articles/101000440020-make-your-first-octopart-supply-data-query

Nexar has grown and so the best way to get rapid support is to use the helpdesk and submit a ticket:
https://support.nexar.com/support/tickets/new

**Comment by vmetodiev** [comment]
Hi @RobAltium ,

I have just submitted a ticket. Thank you!
